<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TestSuiteDB</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>25678afa-b36b-4dcd-88b9-2388a0d1a73f</testSuiteGuid>
   <testCaseLink>
      <guid>1ed3f48c-6d3f-4372-a7c5-7071bb56cbdc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/100201_D/TestDataDriven</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>2ed4c57a-5800-411b-80fc-22279d268945</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Test DataAsDB</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>2ed4c57a-5800-411b-80fc-22279d268945</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>ID</value>
         <variableId>0ccaf682-dacc-4931-a5bc-9cad6c113565</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>2ed4c57a-5800-411b-80fc-22279d268945</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>pass</value>
         <variableId>68be8267-98f4-4057-9240-6c0f3ff2fc56</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
