<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_検索</name>
   <tag></tag>
   <elementGuidId>d2a51256-9c0e-495a-9d29-52eb97e94e2b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnZipSch']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btnZipSch</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5d6335bc-6929-4425-9d32-496c3fd20be5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a95a4ee4-fd5c-438e-895e-fc8e6b2843da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>register-search__btn btn waves-effect waves-light</value>
      <webElementGuid>c300eac8-b1f2-4682-b2a6-2f620b0a53f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnZipSch</value>
      <webElementGuid>054ed7ba-2011-4a8e-b96f-e72e9d829da5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>btnZipSch</value>
      <webElementGuid>2630b4af-2462-4d19-8a5e-2ea64eb953f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>検索</value>
      <webElementGuid>219edb82-e8fc-4055-92aa-656452f6f8a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnZipSch&quot;)</value>
      <webElementGuid>3f80bc59-e82e-4e58-873e-0bb81916084f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnZipSch']</value>
      <webElementGuid>d3b80bcc-b28d-41bd-88f2-c631e3718b0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmschzip']/div[2]/button</value>
      <webElementGuid>09aa9243-873a-4618-9119-2eeaaaec7768</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='郵便番号から検索'])[1]/following::button[1]</value>
      <webElementGuid>a83bda56-516b-4a9a-9b8d-f2108503aa61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='新規登録'])[1]/following::button[1]</value>
      <webElementGuid>6e78fb9d-b6e9-484b-9bb6-1a674143cbf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ご住所から検索'])[1]/preceding::button[1]</value>
      <webElementGuid>33c89f41-ff7e-4eba-84ad-fab37528784f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='都道府県'])[1]/preceding::button[1]</value>
      <webElementGuid>9088d709-5df2-4830-b609-84d8a435b599</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='検索']/parent::*</value>
      <webElementGuid>192964e3-fc77-42ce-ad45-a34949791d7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>d6fb7cc8-8bed-4e47-b85c-7c955c261d66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'btnZipSch' and @name = 'btnZipSch' and (text() = '検索' or . = '検索')]</value>
      <webElementGuid>3a2f8c6f-765f-4dd7-9045-431cfb48fc12</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
