<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_ 町</name>
   <tag></tag>
   <elementGuidId>602fd937-5310-4a73-a7d5-76a47c8e5f48</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'address' and @name = 'selAddress' and (text() = '選択してください赤平泉町エルム町大町北文京町共和町幸町桜木町昭和町住吉町豊丘町豊里錦町西豊里町西文京町東大町東豊里町東文京町百戸町北百戸町西百戸町東平岸曙町平岸桂町平岸新光町平岸仲町平岸西町平岸東町平岸南町豊栄町幌岡町本町美園町宮下町茂尻茂尻旭町茂尻春日町茂尻栄町茂尻新春日町茂尻新町茂尻中央町北茂尻中央町南茂尻本町茂尻宮下町茂尻元町北茂尻元町南若木町北若木町西若木町東若木町南' or . = '選択してください赤平泉町エルム町大町北文京町共和町幸町桜木町昭和町住吉町豊丘町豊里錦町西豊里町西文京町東大町東豊里町東文京町百戸町北百戸町西百戸町東平岸曙町平岸桂町平岸新光町平岸仲町平岸西町平岸東町平岸南町豊栄町幌岡町本町美園町宮下町茂尻茂尻旭町茂尻春日町茂尻栄町茂尻新春日町茂尻新町茂尻中央町北茂尻中央町南茂尻本町茂尻宮下町茂尻元町北茂尻元町南若木町北若木町西若木町東若木町南')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='address']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#address</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>a0cdc049-0617-47ba-b2b7-5bd32dd89930</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>browser-default</value>
      <webElementGuid>46a2f6f0-48ba-492a-b81f-accf2c7c511d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>address</value>
      <webElementGuid>591688ed-42af-457b-b7cb-cfeb9c109dfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>selAddress</value>
      <webElementGuid>14a62d71-1f3c-41ae-bb13-a4fc45a14361</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>選択してください赤平泉町エルム町大町北文京町共和町幸町桜木町昭和町住吉町豊丘町豊里錦町西豊里町西文京町東大町東豊里町東文京町百戸町北百戸町西百戸町東平岸曙町平岸桂町平岸新光町平岸仲町平岸西町平岸東町平岸南町豊栄町幌岡町本町美園町宮下町茂尻茂尻旭町茂尻春日町茂尻栄町茂尻新春日町茂尻新町茂尻中央町北茂尻中央町南茂尻本町茂尻宮下町茂尻元町北茂尻元町南若木町北若木町西若木町東若木町南</value>
      <webElementGuid>801e399d-9805-4e91-9b8d-90a48c4fca87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;address&quot;)</value>
      <webElementGuid>0ec505a1-3593-4999-ba1c-01857b6ef324</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='address']</value>
      <webElementGuid>cb8bbb5d-4be9-4a3d-be71-ea35ca369e21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmschaddr']/div/div[3]/select</value>
      <webElementGuid>cd8e7a37-b175-46f2-9664-0eb076befad3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='町域'])[1]/following::select[1]</value>
      <webElementGuid>f8fb75ee-50fe-4d1d-a98b-3c9acf216fa7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='市区郡'])[1]/following::select[2]</value>
      <webElementGuid>c2fae582-907f-43a5-87fa-063dd3ec4a4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='検索'])[2]/preceding::select[1]</value>
      <webElementGuid>4a26ccb9-1b46-4468-aaf1-b4a8412caa97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ログインページに戻る'])[1]/preceding::select[1]</value>
      <webElementGuid>b8c68621-4542-41ac-be54-3c213f7d3f7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/select</value>
      <webElementGuid>d019fd0b-52cc-4f51-bc56-a2549d3357b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'address' and @name = 'selAddress' and (text() = '選択してください赤平泉町エルム町大町北文京町共和町幸町桜木町昭和町住吉町豊丘町豊里錦町西豊里町西文京町東大町東豊里町東文京町百戸町北百戸町西百戸町東平岸曙町平岸桂町平岸新光町平岸仲町平岸西町平岸東町平岸南町豊栄町幌岡町本町美園町宮下町茂尻茂尻旭町茂尻春日町茂尻栄町茂尻新春日町茂尻新町茂尻中央町北茂尻中央町南茂尻本町茂尻宮下町茂尻元町北茂尻元町南若木町北若木町西若木町東若木町南' or . = '選択してください赤平泉町エルム町大町北文京町共和町幸町桜木町昭和町住吉町豊丘町豊里錦町西豊里町西文京町東大町東豊里町東文京町百戸町北百戸町西百戸町東平岸曙町平岸桂町平岸新光町平岸仲町平岸西町平岸東町平岸南町豊栄町幌岡町本町美園町宮下町茂尻茂尻旭町茂尻春日町茂尻栄町茂尻新春日町茂尻新町茂尻中央町北茂尻中央町南茂尻本町茂尻宮下町茂尻元町北茂尻元町南若木町北若木町西若木町東若木町南')]</value>
      <webElementGuid>b4ed8480-4602-4dd3-a430-e95f2f3ec460</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
