<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_県</name>
   <tag></tag>
   <elementGuidId>75e66d80-0241-4213-b686-f45160256601</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='pref']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#pref</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>ea92a31f-8288-4e65-baeb-7f60fb928191</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>browser-default</value>
      <webElementGuid>3a5f26ec-2ecc-41ba-a57c-99ad3d5dbabe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pref</value>
      <webElementGuid>5d8eae0b-a82c-48a8-930c-0001571c55af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>selPref</value>
      <webElementGuid>57d634fb-3c75-4d1e-bca3-d9098da0f0bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
													選択してください
													北海道
													青森県
													岩手県
													宮城県
													秋田県
													山形県
													福島県
													茨城県
													栃木県
													群馬県
													埼玉県
													千葉県
													東京都
													神奈川県
													新潟県
													富山県
													石川県
													福井県
													山梨県
													長野県
													岐阜県
													静岡県
													愛知県
													三重県
													滋賀県
													京都府
													大阪府
													兵庫県
													奈良県
													和歌山県
													鳥取県
													島根県
													岡山県
													広島県
													山口県
													徳島県
													香川県
													愛媛県
													高知県
													福岡県
													佐賀県
													長崎県
													熊本県
													大分県
													宮崎県
													鹿児島県
													沖縄県
												</value>
      <webElementGuid>ed303fd2-442d-4688-afd0-b029957809fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pref&quot;)</value>
      <webElementGuid>74a2ede4-ebe6-410c-965a-4f2e001511f2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='pref']</value>
      <webElementGuid>c46f546a-c182-4ce9-911f-001b521e88fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmschaddr']/div/div/select</value>
      <webElementGuid>a10d5b69-8d96-4a32-bdfa-83678be7724b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='都道府県'])[1]/following::select[1]</value>
      <webElementGuid>a90c13c8-5303-4380-ac01-0d8673077be0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ご住所から検索'])[1]/following::select[1]</value>
      <webElementGuid>44b71945-b7ef-4396-94bc-293818aca051</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='市区郡'])[1]/preceding::select[1]</value>
      <webElementGuid>1ed7faed-db9e-4349-8e02-485e7bb43ac7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='町域'])[1]/preceding::select[2]</value>
      <webElementGuid>600c3bc5-f2a9-451a-9842-15ac39be13e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>a0291622-f496-4c5a-b31f-feb688f6ef57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'pref' and @name = 'selPref' and (text() = '
													選択してください
													北海道
													青森県
													岩手県
													宮城県
													秋田県
													山形県
													福島県
													茨城県
													栃木県
													群馬県
													埼玉県
													千葉県
													東京都
													神奈川県
													新潟県
													富山県
													石川県
													福井県
													山梨県
													長野県
													岐阜県
													静岡県
													愛知県
													三重県
													滋賀県
													京都府
													大阪府
													兵庫県
													奈良県
													和歌山県
													鳥取県
													島根県
													岡山県
													広島県
													山口県
													徳島県
													香川県
													愛媛県
													高知県
													福岡県
													佐賀県
													長崎県
													熊本県
													大分県
													宮崎県
													鹿児島県
													沖縄県
												' or . = '
													選択してください
													北海道
													青森県
													岩手県
													宮城県
													秋田県
													山形県
													福島県
													茨城県
													栃木県
													群馬県
													埼玉県
													千葉県
													東京都
													神奈川県
													新潟県
													富山県
													石川県
													福井県
													山梨県
													長野県
													岐阜県
													静岡県
													愛知県
													三重県
													滋賀県
													京都府
													大阪府
													兵庫県
													奈良県
													和歌山県
													鳥取県
													島根県
													岡山県
													広島県
													山口県
													徳島県
													香川県
													愛媛県
													高知県
													福岡県
													佐賀県
													長崎県
													熊本県
													大分県
													宮崎県
													鹿児島県
													沖縄県
												')]</value>
      <webElementGuid>08a2ad91-f85c-48d9-8c52-36ad3b8981ef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
