<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_市区</name>
   <tag></tag>
   <elementGuidId>ef3ab9d0-ba84-4dca-910a-53c5d998ab21</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'city' and @name = 'selCity' and (text() = '選択してください赤平市阿寒郡鶴居村旭川市芦別市足寄郡足寄町足寄郡陸別町厚岸郡厚岸町厚岸郡浜中町網走郡大空町網走郡津別町網走郡美幌町網走市虻田郡喜茂別町虻田郡京極町虻田郡倶知安町虻田郡洞爺湖町虻田郡豊浦町虻田郡ニセコ町虻田郡真狩村虻田郡留寿都村石狩郡新篠津村石狩郡当別町石狩市磯谷郡蘭越町岩内郡岩内町岩内郡共和町岩見沢市有珠郡壮瞥町歌志内市浦河郡浦河町雨竜郡雨竜町雨竜郡秩父別町雨竜郡沼田町雨竜郡北竜町雨竜郡幌加内町雨竜郡妹背牛町枝幸郡枝幸町枝幸郡中頓別町枝幸郡浜頓別町恵庭市江別市奥尻郡奥尻町小樽市帯広市河西郡更別村河西郡中札内村河西郡芽室町河東郡音更町河東郡上士幌町河東郡鹿追町河東郡士幌町樺戸郡浦臼町樺戸郡新十津川町樺戸郡月形町上磯郡木古内町上磯郡知内町上川郡愛別町上川郡上川町上川郡剣淵町上川郡清水町上川郡下川町上川郡新得町上川郡鷹栖町上川郡当麻町上川郡美瑛町上川郡東神楽町上川郡東川町上川郡比布町上川郡和寒町亀田郡七飯町茅部郡鹿部町茅部郡森町川上郡標茶町川上郡弟子屈町北広島市北見市釧路郡釧路町釧路市久遠郡せたな町札幌市厚別区札幌市北区札幌市清田区札幌市白石区札幌市中央区札幌市手稲区札幌市豊平区札幌市西区札幌市東区札幌市南区様似郡様似町沙流郡日高町沙流郡平取町標津郡標津町標津郡中標津町士別市島牧郡島牧村積丹郡積丹町斜里郡清里町斜里郡小清水町斜里郡斜里町白老郡白老町白糠郡白糠町寿都郡黒松内町寿都郡寿都町砂川市瀬棚郡今金町宗谷郡猿払村空知郡上砂川町空知郡上富良野町空知郡奈井江町空知郡中富良野町空知郡南幌町空知郡南富良野町滝川市伊達市千歳市天塩郡遠別町天塩郡天塩町天塩郡豊富町天塩郡幌延町十勝郡浦幌町常呂郡置戸町常呂郡訓子府町常呂郡佐呂間町苫小牧市苫前郡初山別村苫前郡苫前町苫前郡羽幌町中川郡池田町中川郡音威子府村中川郡豊頃町中川郡中川町中川郡美深町中川郡本別町中川郡幕別町名寄市新冠郡新冠町爾志郡乙部町根室市野付郡別海町登別市函館市日高郡新ひだか町美唄市檜山郡厚沢部町檜山郡江差町檜山郡上ノ国町広尾郡大樹町広尾郡広尾町深川市二海郡八雲町富良野市古宇郡神恵内村古宇郡泊村古平郡古平町北斗市幌泉郡えりも町増毛郡増毛町松前郡福島町松前郡松前町三笠市室蘭市目梨郡羅臼町紋別郡遠軽町紋別郡雄武町紋別郡興部町紋別郡滝上町紋別郡西興部村紋別郡湧別町紋別市山越郡長万部町夕張郡栗山町夕張郡長沼町夕張郡由仁町夕張市勇払郡厚真町勇払郡安平町勇払郡占冠村勇払郡むかわ町余市郡赤井川村余市郡仁木町余市郡余市町利尻郡利尻町利尻郡利尻富士町留萌郡小平町留萌市礼文郡礼文町稚内市' or . = '選択してください赤平市阿寒郡鶴居村旭川市芦別市足寄郡足寄町足寄郡陸別町厚岸郡厚岸町厚岸郡浜中町網走郡大空町網走郡津別町網走郡美幌町網走市虻田郡喜茂別町虻田郡京極町虻田郡倶知安町虻田郡洞爺湖町虻田郡豊浦町虻田郡ニセコ町虻田郡真狩村虻田郡留寿都村石狩郡新篠津村石狩郡当別町石狩市磯谷郡蘭越町岩内郡岩内町岩内郡共和町岩見沢市有珠郡壮瞥町歌志内市浦河郡浦河町雨竜郡雨竜町雨竜郡秩父別町雨竜郡沼田町雨竜郡北竜町雨竜郡幌加内町雨竜郡妹背牛町枝幸郡枝幸町枝幸郡中頓別町枝幸郡浜頓別町恵庭市江別市奥尻郡奥尻町小樽市帯広市河西郡更別村河西郡中札内村河西郡芽室町河東郡音更町河東郡上士幌町河東郡鹿追町河東郡士幌町樺戸郡浦臼町樺戸郡新十津川町樺戸郡月形町上磯郡木古内町上磯郡知内町上川郡愛別町上川郡上川町上川郡剣淵町上川郡清水町上川郡下川町上川郡新得町上川郡鷹栖町上川郡当麻町上川郡美瑛町上川郡東神楽町上川郡東川町上川郡比布町上川郡和寒町亀田郡七飯町茅部郡鹿部町茅部郡森町川上郡標茶町川上郡弟子屈町北広島市北見市釧路郡釧路町釧路市久遠郡せたな町札幌市厚別区札幌市北区札幌市清田区札幌市白石区札幌市中央区札幌市手稲区札幌市豊平区札幌市西区札幌市東区札幌市南区様似郡様似町沙流郡日高町沙流郡平取町標津郡標津町標津郡中標津町士別市島牧郡島牧村積丹郡積丹町斜里郡清里町斜里郡小清水町斜里郡斜里町白老郡白老町白糠郡白糠町寿都郡黒松内町寿都郡寿都町砂川市瀬棚郡今金町宗谷郡猿払村空知郡上砂川町空知郡上富良野町空知郡奈井江町空知郡中富良野町空知郡南幌町空知郡南富良野町滝川市伊達市千歳市天塩郡遠別町天塩郡天塩町天塩郡豊富町天塩郡幌延町十勝郡浦幌町常呂郡置戸町常呂郡訓子府町常呂郡佐呂間町苫小牧市苫前郡初山別村苫前郡苫前町苫前郡羽幌町中川郡池田町中川郡音威子府村中川郡豊頃町中川郡中川町中川郡美深町中川郡本別町中川郡幕別町名寄市新冠郡新冠町爾志郡乙部町根室市野付郡別海町登別市函館市日高郡新ひだか町美唄市檜山郡厚沢部町檜山郡江差町檜山郡上ノ国町広尾郡大樹町広尾郡広尾町深川市二海郡八雲町富良野市古宇郡神恵内村古宇郡泊村古平郡古平町北斗市幌泉郡えりも町増毛郡増毛町松前郡福島町松前郡松前町三笠市室蘭市目梨郡羅臼町紋別郡遠軽町紋別郡雄武町紋別郡興部町紋別郡滝上町紋別郡西興部村紋別郡湧別町紋別市山越郡長万部町夕張郡栗山町夕張郡長沼町夕張郡由仁町夕張市勇払郡厚真町勇払郡安平町勇払郡占冠村勇払郡むかわ町余市郡赤井川村余市郡仁木町余市郡余市町利尻郡利尻町利尻郡利尻富士町留萌郡小平町留萌市礼文郡礼文町稚内市')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='city']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#city</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>58a7ca7d-2b44-4068-b2e8-a118dcb55eb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>browser-default</value>
      <webElementGuid>9642f246-cff1-46a8-8c02-e74cde6e6ead</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>city</value>
      <webElementGuid>4277399a-0f7a-44dd-844f-4d560d26c046</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>selCity</value>
      <webElementGuid>2d4b9bc2-2f00-4ab2-9e36-4e6eb70b7a33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>選択してください赤平市阿寒郡鶴居村旭川市芦別市足寄郡足寄町足寄郡陸別町厚岸郡厚岸町厚岸郡浜中町網走郡大空町網走郡津別町網走郡美幌町網走市虻田郡喜茂別町虻田郡京極町虻田郡倶知安町虻田郡洞爺湖町虻田郡豊浦町虻田郡ニセコ町虻田郡真狩村虻田郡留寿都村石狩郡新篠津村石狩郡当別町石狩市磯谷郡蘭越町岩内郡岩内町岩内郡共和町岩見沢市有珠郡壮瞥町歌志内市浦河郡浦河町雨竜郡雨竜町雨竜郡秩父別町雨竜郡沼田町雨竜郡北竜町雨竜郡幌加内町雨竜郡妹背牛町枝幸郡枝幸町枝幸郡中頓別町枝幸郡浜頓別町恵庭市江別市奥尻郡奥尻町小樽市帯広市河西郡更別村河西郡中札内村河西郡芽室町河東郡音更町河東郡上士幌町河東郡鹿追町河東郡士幌町樺戸郡浦臼町樺戸郡新十津川町樺戸郡月形町上磯郡木古内町上磯郡知内町上川郡愛別町上川郡上川町上川郡剣淵町上川郡清水町上川郡下川町上川郡新得町上川郡鷹栖町上川郡当麻町上川郡美瑛町上川郡東神楽町上川郡東川町上川郡比布町上川郡和寒町亀田郡七飯町茅部郡鹿部町茅部郡森町川上郡標茶町川上郡弟子屈町北広島市北見市釧路郡釧路町釧路市久遠郡せたな町札幌市厚別区札幌市北区札幌市清田区札幌市白石区札幌市中央区札幌市手稲区札幌市豊平区札幌市西区札幌市東区札幌市南区様似郡様似町沙流郡日高町沙流郡平取町標津郡標津町標津郡中標津町士別市島牧郡島牧村積丹郡積丹町斜里郡清里町斜里郡小清水町斜里郡斜里町白老郡白老町白糠郡白糠町寿都郡黒松内町寿都郡寿都町砂川市瀬棚郡今金町宗谷郡猿払村空知郡上砂川町空知郡上富良野町空知郡奈井江町空知郡中富良野町空知郡南幌町空知郡南富良野町滝川市伊達市千歳市天塩郡遠別町天塩郡天塩町天塩郡豊富町天塩郡幌延町十勝郡浦幌町常呂郡置戸町常呂郡訓子府町常呂郡佐呂間町苫小牧市苫前郡初山別村苫前郡苫前町苫前郡羽幌町中川郡池田町中川郡音威子府村中川郡豊頃町中川郡中川町中川郡美深町中川郡本別町中川郡幕別町名寄市新冠郡新冠町爾志郡乙部町根室市野付郡別海町登別市函館市日高郡新ひだか町美唄市檜山郡厚沢部町檜山郡江差町檜山郡上ノ国町広尾郡大樹町広尾郡広尾町深川市二海郡八雲町富良野市古宇郡神恵内村古宇郡泊村古平郡古平町北斗市幌泉郡えりも町増毛郡増毛町松前郡福島町松前郡松前町三笠市室蘭市目梨郡羅臼町紋別郡遠軽町紋別郡雄武町紋別郡興部町紋別郡滝上町紋別郡西興部村紋別郡湧別町紋別市山越郡長万部町夕張郡栗山町夕張郡長沼町夕張郡由仁町夕張市勇払郡厚真町勇払郡安平町勇払郡占冠村勇払郡むかわ町余市郡赤井川村余市郡仁木町余市郡余市町利尻郡利尻町利尻郡利尻富士町留萌郡小平町留萌市礼文郡礼文町稚内市</value>
      <webElementGuid>55c558e1-360e-4ebf-82cf-18a6c445f95d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;city&quot;)</value>
      <webElementGuid>ae4bbf67-3972-4145-83e1-f5882db75cc6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='city']</value>
      <webElementGuid>898f8885-a0f0-40cb-9334-5e9f074e5108</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmschaddr']/div/div[2]/select</value>
      <webElementGuid>f937b9a2-f890-41dc-8ea3-8b5f767fa12c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='市区郡'])[1]/following::select[1]</value>
      <webElementGuid>d69fa175-5a22-4c61-a2b7-1f3819b0a6d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='都道府県'])[1]/following::select[2]</value>
      <webElementGuid>1f32d0e6-b360-43c3-b9eb-d8343a56701e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='町域'])[1]/preceding::select[1]</value>
      <webElementGuid>2cf58893-2c21-4c44-9083-019391c42137</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='検索'])[2]/preceding::select[2]</value>
      <webElementGuid>bcb25d13-3e14-4065-8a7a-8433687200c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/select</value>
      <webElementGuid>1521e626-4057-4f0b-9ef3-6cf01fb8001c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'city' and @name = 'selCity' and (text() = '選択してください赤平市阿寒郡鶴居村旭川市芦別市足寄郡足寄町足寄郡陸別町厚岸郡厚岸町厚岸郡浜中町網走郡大空町網走郡津別町網走郡美幌町網走市虻田郡喜茂別町虻田郡京極町虻田郡倶知安町虻田郡洞爺湖町虻田郡豊浦町虻田郡ニセコ町虻田郡真狩村虻田郡留寿都村石狩郡新篠津村石狩郡当別町石狩市磯谷郡蘭越町岩内郡岩内町岩内郡共和町岩見沢市有珠郡壮瞥町歌志内市浦河郡浦河町雨竜郡雨竜町雨竜郡秩父別町雨竜郡沼田町雨竜郡北竜町雨竜郡幌加内町雨竜郡妹背牛町枝幸郡枝幸町枝幸郡中頓別町枝幸郡浜頓別町恵庭市江別市奥尻郡奥尻町小樽市帯広市河西郡更別村河西郡中札内村河西郡芽室町河東郡音更町河東郡上士幌町河東郡鹿追町河東郡士幌町樺戸郡浦臼町樺戸郡新十津川町樺戸郡月形町上磯郡木古内町上磯郡知内町上川郡愛別町上川郡上川町上川郡剣淵町上川郡清水町上川郡下川町上川郡新得町上川郡鷹栖町上川郡当麻町上川郡美瑛町上川郡東神楽町上川郡東川町上川郡比布町上川郡和寒町亀田郡七飯町茅部郡鹿部町茅部郡森町川上郡標茶町川上郡弟子屈町北広島市北見市釧路郡釧路町釧路市久遠郡せたな町札幌市厚別区札幌市北区札幌市清田区札幌市白石区札幌市中央区札幌市手稲区札幌市豊平区札幌市西区札幌市東区札幌市南区様似郡様似町沙流郡日高町沙流郡平取町標津郡標津町標津郡中標津町士別市島牧郡島牧村積丹郡積丹町斜里郡清里町斜里郡小清水町斜里郡斜里町白老郡白老町白糠郡白糠町寿都郡黒松内町寿都郡寿都町砂川市瀬棚郡今金町宗谷郡猿払村空知郡上砂川町空知郡上富良野町空知郡奈井江町空知郡中富良野町空知郡南幌町空知郡南富良野町滝川市伊達市千歳市天塩郡遠別町天塩郡天塩町天塩郡豊富町天塩郡幌延町十勝郡浦幌町常呂郡置戸町常呂郡訓子府町常呂郡佐呂間町苫小牧市苫前郡初山別村苫前郡苫前町苫前郡羽幌町中川郡池田町中川郡音威子府村中川郡豊頃町中川郡中川町中川郡美深町中川郡本別町中川郡幕別町名寄市新冠郡新冠町爾志郡乙部町根室市野付郡別海町登別市函館市日高郡新ひだか町美唄市檜山郡厚沢部町檜山郡江差町檜山郡上ノ国町広尾郡大樹町広尾郡広尾町深川市二海郡八雲町富良野市古宇郡神恵内村古宇郡泊村古平郡古平町北斗市幌泉郡えりも町増毛郡増毛町松前郡福島町松前郡松前町三笠市室蘭市目梨郡羅臼町紋別郡遠軽町紋別郡雄武町紋別郡興部町紋別郡滝上町紋別郡西興部村紋別郡湧別町紋別市山越郡長万部町夕張郡栗山町夕張郡長沼町夕張郡由仁町夕張市勇払郡厚真町勇払郡安平町勇払郡占冠村勇払郡むかわ町余市郡赤井川村余市郡仁木町余市郡余市町利尻郡利尻町利尻郡利尻富士町留萌郡小平町留萌市礼文郡礼文町稚内市' or . = '選択してください赤平市阿寒郡鶴居村旭川市芦別市足寄郡足寄町足寄郡陸別町厚岸郡厚岸町厚岸郡浜中町網走郡大空町網走郡津別町網走郡美幌町網走市虻田郡喜茂別町虻田郡京極町虻田郡倶知安町虻田郡洞爺湖町虻田郡豊浦町虻田郡ニセコ町虻田郡真狩村虻田郡留寿都村石狩郡新篠津村石狩郡当別町石狩市磯谷郡蘭越町岩内郡岩内町岩内郡共和町岩見沢市有珠郡壮瞥町歌志内市浦河郡浦河町雨竜郡雨竜町雨竜郡秩父別町雨竜郡沼田町雨竜郡北竜町雨竜郡幌加内町雨竜郡妹背牛町枝幸郡枝幸町枝幸郡中頓別町枝幸郡浜頓別町恵庭市江別市奥尻郡奥尻町小樽市帯広市河西郡更別村河西郡中札内村河西郡芽室町河東郡音更町河東郡上士幌町河東郡鹿追町河東郡士幌町樺戸郡浦臼町樺戸郡新十津川町樺戸郡月形町上磯郡木古内町上磯郡知内町上川郡愛別町上川郡上川町上川郡剣淵町上川郡清水町上川郡下川町上川郡新得町上川郡鷹栖町上川郡当麻町上川郡美瑛町上川郡東神楽町上川郡東川町上川郡比布町上川郡和寒町亀田郡七飯町茅部郡鹿部町茅部郡森町川上郡標茶町川上郡弟子屈町北広島市北見市釧路郡釧路町釧路市久遠郡せたな町札幌市厚別区札幌市北区札幌市清田区札幌市白石区札幌市中央区札幌市手稲区札幌市豊平区札幌市西区札幌市東区札幌市南区様似郡様似町沙流郡日高町沙流郡平取町標津郡標津町標津郡中標津町士別市島牧郡島牧村積丹郡積丹町斜里郡清里町斜里郡小清水町斜里郡斜里町白老郡白老町白糠郡白糠町寿都郡黒松内町寿都郡寿都町砂川市瀬棚郡今金町宗谷郡猿払村空知郡上砂川町空知郡上富良野町空知郡奈井江町空知郡中富良野町空知郡南幌町空知郡南富良野町滝川市伊達市千歳市天塩郡遠別町天塩郡天塩町天塩郡豊富町天塩郡幌延町十勝郡浦幌町常呂郡置戸町常呂郡訓子府町常呂郡佐呂間町苫小牧市苫前郡初山別村苫前郡苫前町苫前郡羽幌町中川郡池田町中川郡音威子府村中川郡豊頃町中川郡中川町中川郡美深町中川郡本別町中川郡幕別町名寄市新冠郡新冠町爾志郡乙部町根室市野付郡別海町登別市函館市日高郡新ひだか町美唄市檜山郡厚沢部町檜山郡江差町檜山郡上ノ国町広尾郡大樹町広尾郡広尾町深川市二海郡八雲町富良野市古宇郡神恵内村古宇郡泊村古平郡古平町北斗市幌泉郡えりも町増毛郡増毛町松前郡福島町松前郡松前町三笠市室蘭市目梨郡羅臼町紋別郡遠軽町紋別郡雄武町紋別郡興部町紋別郡滝上町紋別郡西興部村紋別郡湧別町紋別市山越郡長万部町夕張郡栗山町夕張郡長沼町夕張郡由仁町夕張市勇払郡厚真町勇払郡安平町勇払郡占冠村勇払郡むかわ町余市郡赤井川村余市郡仁木町余市郡余市町利尻郡利尻町利尻郡利尻富士町留萌郡小平町留萌市礼文郡礼文町稚内市')]</value>
      <webElementGuid>ef194e9b-439b-4f6e-bcd9-a71acbc0fa14</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
