<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe__iframeResult</name>
   <tag></tag>
   <elementGuidId>767e14f7-d846-4346-9821-23dc3a1740f2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='iframeResult']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#iframeResult</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>ce395c95-d302-4a5a-a03d-2f0b58af902f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>a185774f-3e04-4ce0-8d11-3f9fdb63ca63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>iframeResult</value>
      <webElementGuid>7b7b293a-27e7-4afe-be6d-c7f15a3b2ca0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>iframeResult</value>
      <webElementGuid>ff4a6195-4267-4e28-843b-f06c4ece207d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allowfullscreen</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a881a2b0-8265-45ad-b5dc-da84103ca787</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;iframeResult&quot;)</value>
      <webElementGuid>059983a5-442a-433e-98a7-9d67defbe320</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='iframeResult']</value>
      <webElementGuid>2f3c143e-6998-47a6-8cfa-726fab8cffd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='iframewrapper']/iframe</value>
      <webElementGuid>5c4185e6-ae5f-4b96-9850-0fd402fc7a73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/iframe</value>
      <webElementGuid>bbf554a8-25f0-44cd-ad0e-e0141d65a402</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'iframeResult' and @name = 'iframeResult']</value>
      <webElementGuid>dd335321-c368-4c38-80b3-6f894a0ac0ea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
