<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__txtUse_Name</name>
   <tag></tag>
   <elementGuidId>a3ede1f7-7f45-436a-9639-2ec3cfa505b9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtUse_Name']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txtUse_Name</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2b97229c-3add-4271-adad-1c6296e058a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>70e5dab7-ea69-406c-8a87-776824f342c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>kana</value>
      <webElementGuid>ee026dbb-6e41-45a0-9b0b-6bd2775bc6b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>全角（例：ヨシケイ　太郎）</value>
      <webElementGuid>34444b5b-9d13-45ec-ad6a-80876affe36e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtUse_Name</value>
      <webElementGuid>89dc4932-7bac-470e-97e1-44e57d6d9776</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtUse_Name</value>
      <webElementGuid>2c8dc76c-7752-4515-ba7f-427899ab07a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>e78a9a94-a251-408b-bb50-2c1fa453a722</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtUse_Name&quot;)</value>
      <webElementGuid>0c53a023-9bc4-425f-b7a6-ae7cbc6a9c1c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtUse_Name']</value>
      <webElementGuid>e985a94f-3a88-46a9-840b-1495993a759a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmsch']/table/tbody/tr[2]/td[2]/input</value>
      <webElementGuid>d262b16f-f970-44d6-ba5e-0b4f78e3b2cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>82373ba6-081f-46bf-8ebc-f4a27d6fffc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = '全角（例：ヨシケイ　太郎）' and @id = 'txtUse_Name' and @name = 'txtUse_Name']</value>
      <webElementGuid>91209a99-23dd-4178-ab03-235408dc6ff2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
