<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_お名前Label</name>
   <tag></tag>
   <elementGuidId>c74d7a42-154b-4930-ae8d-168f622b38dc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='frmsch']/table/tbody/tr[2]/th/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>7f77b268-efa1-4e99-8e0d-3432fc6ef5e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>lblUse_Name</value>
      <webElementGuid>370a0af6-91e7-4342-9aea-9376b8dc73f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>お名前</value>
      <webElementGuid>25379854-bad2-4d25-8908-95b7323c43e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmsch&quot;)/table[@class=&quot;form-table&quot;]/tbody[1]/tr[2]/th[1]/label[1]</value>
      <webElementGuid>bea0ebba-0f05-4fe6-b55f-1884d5bc6e45</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmsch']/table/tbody/tr[2]/th/label</value>
      <webElementGuid>6fef849a-83d8-4d5d-8921-0c01742697ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ヨシケイ東部'])[2]/following::label[1]</value>
      <webElementGuid>7a765773-8a81-4907-a1cf-4ffeb78f38e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='担当店'])[1]/following::label[1]</value>
      <webElementGuid>6de18a1d-40b1-4f3a-b8cb-4d0a54163f46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='必須'])[1]/preceding::label[1]</value>
      <webElementGuid>954020d2-5964-49d6-bbe8-b9376a7c29c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='お名前（カタカナ）'])[1]/preceding::label[1]</value>
      <webElementGuid>cf42a4ad-b12b-4201-a664-ce12f5d3f47c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='お名前']/parent::*</value>
      <webElementGuid>2cff183c-2ea7-4270-8576-e4a676cd2935</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/th/label</value>
      <webElementGuid>e6325f86-11f5-4bfe-8ea0-a664496a78cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'お名前' or . = 'お名前')]</value>
      <webElementGuid>80a622e1-8e39-4590-a986-ffbfc771e763</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
