<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_お名前を入力してください</name>
   <tag></tag>
   <elementGuidId>76ff92c3-33fe-47f1-b473-7f4eef5a7d5c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='errMsgArea']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#errMsgArea</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>4ad18fc9-93cf-452b-a025-1a93baaa5a4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>errMsgArea</value>
      <webElementGuid>5871dbd3-feb1-4561-986b-f68d4e349787</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>txtUse_Name_msg form__error</value>
      <webElementGuid>c308a3fd-6e77-4dae-a686-d988b211a028</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>お名前を入力してください。</value>
      <webElementGuid>4f961992-4eaa-4fd8-917d-9758c681c224</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmsch&quot;)/table[@class=&quot;form-table&quot;]/tbody[1]/tr[2]/td[2]/p[@id=&quot;errMsgArea&quot;]</value>
      <webElementGuid>49d2b129-cbd3-4dcb-a854-17b37e84ca36</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='errMsgArea']</value>
      <webElementGuid>dcc62436-31d9-4470-b7d4-67e7c5397be9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmsch']/table/tbody/tr[2]/td[2]/p</value>
      <webElementGuid>34acb6a8-f2a0-4862-9230-1a2c3cf52f69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='必須'])[1]/following::p[1]</value>
      <webElementGuid>839671ec-24ca-46f5-a471-4ddd93bdfe24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='お名前'])[1]/following::p[1]</value>
      <webElementGuid>5d5ea420-ca9f-4825-acce-601be043b124</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='お名前（カタカナ）'])[1]/preceding::p[1]</value>
      <webElementGuid>85329f90-4143-47a8-9ddf-707e6f51282c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='必須'])[2]/preceding::p[1]</value>
      <webElementGuid>fa03e09c-4d26-461e-9d55-6e3d823dd2e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='お名前を入力してください。']/parent::*</value>
      <webElementGuid>f9e76e7e-2c6f-48e0-bb08-f21cb6870f71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/p</value>
      <webElementGuid>861e6e44-29b4-481e-8b1d-d4b1e5bf43b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'errMsgArea' and (text() = 'お名前を入力してください。' or . = 'お名前を入力してください。')]</value>
      <webElementGuid>382f12a8-39ac-4679-a7f1-f903f6cd691c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
