<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>th_NameTag</name>
   <tag></tag>
   <elementGuidId>02abc333-93da-4f78-af31-84fb4ffb161d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='frmsch']/table/tbody/tr[3]/th</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>th</value>
      <webElementGuid>869a081e-564e-4e3a-aa27-255a60cb5fc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>お名前（カタカナ）</value>
      <webElementGuid>c9c63d17-e6b9-473b-af27-a0bcbeab4f19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmsch&quot;)/table[@class=&quot;form-table&quot;]/tbody[1]/tr[3]/th[1]</value>
      <webElementGuid>1642a04e-7091-4cf6-9d7d-ae39a61f6321</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmsch']/table/tbody/tr[3]/th</value>
      <webElementGuid>5188b650-0426-41a9-9c20-103ab0e0c5c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='必須'])[1]/following::th[1]</value>
      <webElementGuid>284113ad-cd67-47dc-bfd5-a9c9db4f51a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='お名前'])[1]/following::th[1]</value>
      <webElementGuid>c055526c-112a-4ea2-bfbc-8d4981affde8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='必須'])[2]/preceding::th[1]</value>
      <webElementGuid>f8be95be-ac51-40c1-b4fe-bd1e1fab430c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/th</value>
      <webElementGuid>3c813222-0dc9-4770-a9ff-baa4d178d229</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//th[(text() = 'お名前（カタカナ）' or . = 'お名前（カタカナ）')]</value>
      <webElementGuid>4a8cad99-a529-4fa8-86cb-88eb16f868c1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
