<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_ ヨシケイのレッピ</name>
   <tag></tag>
   <elementGuidId>b4f3920f-5d3a-4b46-a14e-c3c98797ac06</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.help-links__link.link.link--underline</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='wrapper']/div[2]/main/div/div/div/div/ul/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2001c3ae-f784-48da-bff8-cf89a606f67b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>help-links__link link link--underline</value>
      <webElementGuid>b44389ec-0023-4b33-896d-e15107ee03e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>./100361_D.aspx</value>
      <webElementGuid>261d2d90-4f38-4677-9e7d-4b94fa619b21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ヨシケイのレシピはこちら</value>
      <webElementGuid>741274a0-40a2-4208-9bdf-d35d70cf2c30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wrapper&quot;)/div[@class=&quot;site-inner&quot;]/main[@class=&quot;content&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;page-content&quot;]/div[@class=&quot;help-links help-links--login&quot;]/div[@class=&quot;help-links&quot;]/ul[@class=&quot;help-links__list&quot;]/li[@class=&quot;help-links__item&quot;]/a[@class=&quot;help-links__link link link--underline&quot;]</value>
      <webElementGuid>8c9a9b13-071e-4b95-8f56-e4e0b90803f1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wrapper']/div[2]/main/div/div/div/div/ul/li/a</value>
      <webElementGuid>42db9237-3aca-459a-ba36-889c228723ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'ヨシケイのレシピはこちら')]</value>
      <webElementGuid>026e7170-25e8-4ded-887e-5f2a588d8134</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ログイン'])[2]/following::a[1]</value>
      <webElementGuid>4ee79120-c3d0-4387-b121-dac1e5e4bb92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='前に戻る'])[1]/following::a[1]</value>
      <webElementGuid>74d2f2a7-b33d-40c3-8f65-25ea33b432e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ログインID　または　登録メールアドレス'])[1]/preceding::a[1]</value>
      <webElementGuid>4d738f89-ef5c-43fa-868a-83a91522ab51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='パスワード'])[1]/preceding::a[1]</value>
      <webElementGuid>60d649ed-0795-426e-bcd7-da142f51cd1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ヨシケイのレシピはこちら']/parent::*</value>
      <webElementGuid>800c1228-8c45-48ce-9e75-bddeea6e6813</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, './100361_D.aspx')]</value>
      <webElementGuid>92c8bf9a-46c2-4553-8986-12c19f08e479</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/ul/li/a</value>
      <webElementGuid>09aeb2fe-6c5b-4285-b437-c97a0abf0f11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = './100361_D.aspx' and (text() = 'ヨシケイのレシピはこちら' or . = 'ヨシケイのレシピはこちら')]</value>
      <webElementGuid>d10f13e0-7e41-488b-8350-e1760ce8fdae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
