<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_ 中部</name>
   <tag></tag>
   <elementGuidId>675d6aa3-663d-48be-915e-b127470003f1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='wrapper']/div[2]/main/div/div/div[3]/div/ul/li[6]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>246e772f-2d94-4c5f-a6f5-f79e5c9cbc52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>help-links__link link link--underline</value>
      <webElementGuid>6526549a-6bf3-4d0e-9446-4801964e0d44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://www.pit-order.com/webJ/chubu/Login2.php</value>
      <webElementGuid>64853981-5faa-47a0-83d7-c0460e15e507</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>c1e29d47-5412-413a-87d8-db93d11ffedb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>こちらから</value>
      <webElementGuid>3fe29784-7892-43e5-9875-b4c565f07a12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wrapper&quot;)/div[@class=&quot;site-inner&quot;]/main[@class=&quot;content&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;page-content&quot;]/div[@class=&quot;help-links help-links--login&quot;]/div[@class=&quot;help-links&quot;]/ul[@class=&quot;help-links__list&quot;]/li[@class=&quot;help-links__item&quot;]/a[@class=&quot;help-links__link link link--underline&quot;]</value>
      <webElementGuid>e98694fb-ceca-4226-83f3-b55c14fef8be</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wrapper']/div[2]/main/div/div/div[3]/div/ul/li[6]/a</value>
      <webElementGuid>9522359c-f088-4c04-b695-cd2166c1ab22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'こちらから')])[2]</value>
      <webElementGuid>09c99570-0042-45b3-b007-0ba786c87c20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='こちらから'])[1]/following::a[1]</value>
      <webElementGuid>80644b93-98cb-4e47-a237-2feed28ab708</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='こちらから'])[3]/preceding::a[1]</value>
      <webElementGuid>ae4868af-a474-410d-b7b1-bb9443201278</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://www.pit-order.com/webJ/chubu/Login2.php']</value>
      <webElementGuid>23449ae0-ac2a-4a08-988c-d8a8b67a9b86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/ul/li[6]/a</value>
      <webElementGuid>b31f2202-3b25-4e40-b2af-9e331ec0b2b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://www.pit-order.com/webJ/chubu/Login2.php' and (text() = 'こちらから' or . = 'こちらから')]</value>
      <webElementGuid>2d7605f9-f131-4d9a-ba5b-ee95746d7dd2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
