<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_ 佐賀</name>
   <tag></tag>
   <elementGuidId>4f7c0915-f666-49a5-9c60-3a24678a5ca8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='wrapper']/div[2]/main/div/div/div[3]/div/ul/li[8]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a5df47d3-d349-4915-b1e3-0c56cd59996f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>help-links__link link link--underline</value>
      <webElementGuid>a9977e29-28af-4b72-a85c-236b3a0187b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://www.pit-order.com/webJ/saga/Login2.php</value>
      <webElementGuid>b928b160-00d8-433c-8fc5-64a4c64247b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>4d02906b-a0d1-4aae-9377-ced346464a40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>こちらから</value>
      <webElementGuid>2e59c4eb-de24-48d2-be96-6262ffb7e9dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wrapper&quot;)/div[@class=&quot;site-inner&quot;]/main[@class=&quot;content&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;page-content&quot;]/div[@class=&quot;help-links help-links--login&quot;]/div[@class=&quot;help-links&quot;]/ul[@class=&quot;help-links__list&quot;]/li[@class=&quot;help-links__item&quot;]/a[@class=&quot;help-links__link link link--underline&quot;]</value>
      <webElementGuid>085447a1-6ae3-4bb3-8432-6a4e21b28c11</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wrapper']/div[2]/main/div/div/div[3]/div/ul/li[8]/a</value>
      <webElementGuid>75d253e1-5537-4b5a-81aa-975cee8a4ec9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'こちらから')])[4]</value>
      <webElementGuid>773af8d9-0cdf-4a80-9b4e-070fbd961f49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='こちらから'])[3]/following::a[1]</value>
      <webElementGuid>d4588009-ea31-4b5e-9ee4-e6500c6dcf6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='トップに戻る'])[1]/preceding::a[1]</value>
      <webElementGuid>aedf9b68-3082-4ad1-91c0-541895aaf101</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::a[2]</value>
      <webElementGuid>b7b3747e-665b-4172-9f68-2de98854c666</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://www.pit-order.com/webJ/saga/Login2.php']</value>
      <webElementGuid>1078fa60-2354-4021-b17b-677b1c3d7702</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/ul/li[8]/a</value>
      <webElementGuid>cfc5d82c-486b-4e3d-9992-c2a4290b2f8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://www.pit-order.com/webJ/saga/Login2.php' and (text() = 'こちらから' or . = 'こちらから')]</value>
      <webElementGuid>bed81ab8-7206-437a-8129-ca094863f671</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
