<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_ 東愛知</name>
   <tag></tag>
   <elementGuidId>aa151196-5749-477c-85fc-c5e7b6499765</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='wrapper']/div[2]/main/div/div/div[3]/div/ul/li[5]/a</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@href = 'http://www.pit-order.com/webJ/higashiaichi/Login2.php' and (text() = 'こちらから' or . = 'こちらから')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1dcb6105-9068-4659-9047-51f988337f9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>help-links__link link link--underline</value>
      <webElementGuid>d6c56012-f97c-4b8f-a07e-6daada236c89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://www.pit-order.com/webJ/higashiaichi/Login2.php</value>
      <webElementGuid>33dd36b1-ef0f-4ce1-b03b-2048f9d00176</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>b7ae2c88-b664-4516-acdb-a383831dcf79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>こちらから</value>
      <webElementGuid>6e08ed8b-b886-4d12-93bd-d85dab79bf85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wrapper&quot;)/div[@class=&quot;site-inner&quot;]/main[@class=&quot;content&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;page-content&quot;]/div[@class=&quot;help-links help-links--login&quot;]/div[@class=&quot;help-links&quot;]/ul[@class=&quot;help-links__list&quot;]/li[@class=&quot;help-links__item&quot;]/a[@class=&quot;help-links__link link link--underline&quot;]</value>
      <webElementGuid>92384f46-d099-477a-840c-221be26c26e0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wrapper']/div[2]/main/div/div/div[3]/div/ul/li[5]/a</value>
      <webElementGuid>63415a31-d8e8-4626-ab28-dc1ed297629f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'こちらから')]</value>
      <webElementGuid>0024d871-f4a5-4fe2-b8fd-3adc95e1daf9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ヨシケイHPに戻る'])[1]/following::a[1]</value>
      <webElementGuid>e40894bb-5874-47c6-98b3-53f2c619c94f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='こちらから'])[2]/preceding::a[1]</value>
      <webElementGuid>d8070133-2a88-4fbf-a07c-d8a8c2526184</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='こちらから']/parent::*</value>
      <webElementGuid>5fb469e7-aeac-481c-b24d-d8adf3aba37c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://www.pit-order.com/webJ/higashiaichi/Login2.php']</value>
      <webElementGuid>274b1586-5d33-4ccb-aaca-66e76dfbba50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/ul/li[5]/a</value>
      <webElementGuid>12825bf4-075e-4836-946d-ea54e006195a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://www.pit-order.com/webJ/higashiaichi/Login2.php' and (text() = 'こちらから' or . = 'こちらから')]</value>
      <webElementGuid>44529be3-03c0-4c38-b52a-563c7aaa695e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
