<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_ 福岡</name>
   <tag></tag>
   <elementGuidId>4d9c486a-2214-4516-ac50-3ce818343dc2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='wrapper']/div[2]/main/div/div/div[3]/div/ul/li[7]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f96315bd-7b17-4858-8b7a-054b806114e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>help-links__link link link--underline</value>
      <webElementGuid>64bd0ffe-3884-484f-915a-d853f79b6e1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://www.pit-order.com/webJ/fukuoka/Login2.php</value>
      <webElementGuid>67415efb-95e3-4d82-a04b-148ad0b3bfdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>8e65593b-7fee-4cd8-aa7f-c780125c8ae2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>こちらから</value>
      <webElementGuid>a2d7f494-9e60-4074-93ff-e357af153e81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wrapper&quot;)/div[@class=&quot;site-inner&quot;]/main[@class=&quot;content&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;page-content&quot;]/div[@class=&quot;help-links help-links--login&quot;]/div[@class=&quot;help-links&quot;]/ul[@class=&quot;help-links__list&quot;]/li[@class=&quot;help-links__item&quot;]/a[@class=&quot;help-links__link link link--underline&quot;]</value>
      <webElementGuid>29126bfa-49cc-48eb-af01-c1e4e79d071b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wrapper']/div[2]/main/div/div/div[3]/div/ul/li[7]/a</value>
      <webElementGuid>42d96ba1-2e86-40b4-a25f-b130728825b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'こちらから')])[3]</value>
      <webElementGuid>567f1399-dd02-443b-be8d-4e34699c258f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='こちらから'])[2]/following::a[1]</value>
      <webElementGuid>14b7a619-648c-4a37-8eaf-1fb991409db0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='こちらから'])[4]/preceding::a[1]</value>
      <webElementGuid>56b0e126-7b32-4e22-88c8-a89647bc98bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://www.pit-order.com/webJ/fukuoka/Login2.php']</value>
      <webElementGuid>8562da4c-315d-4422-9228-ccdc619fda93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/ul/li[7]/a</value>
      <webElementGuid>e65333c2-448b-4ddf-8463-9b48c77d9749</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://www.pit-order.com/webJ/fukuoka/Login2.php' and (text() = 'こちらから' or . = 'こちらから')]</value>
      <webElementGuid>eba808e5-b909-4330-840a-c753ce9b2c98</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
