<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ID_txtWeb_Login_Id</name>
   <tag></tag>
   <elementGuidId>404732a5-1d4a-4384-8d8c-2858f215652a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtWeb_Login_Id</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtWeb_Login_Id']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6d53a2b1-40b4-4a05-9890-33fa1d5e8c6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>validate allow_submit</value>
      <webElementGuid>cb4b8e16-4b06-4f91-9700-1cdc98d5e1db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>648d06af-2075-4046-9be6-c5856aeb895e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>39ba7ab1-66b3-4722-8a4b-a7280ef60926</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtWeb_Login_Id</value>
      <webElementGuid>ec356edf-7319-49a1-ace4-2ab9dff7604f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtWeb_Login_Id</value>
      <webElementGuid>e0056255-810a-48c5-a610-8f950d1c46b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtWeb_Login_Id&quot;)</value>
      <webElementGuid>0504cbe7-61c4-4360-9103-ab22c7d27b8b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtWeb_Login_Id']</value>
      <webElementGuid>39cbdaec-0cea-48d1-9694-accf43505a98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmsch']/div/div/div/input</value>
      <webElementGuid>2f26e2fe-9d65-47cc-b7a8-d9d82df19b7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>4779ad36-334f-4e42-9482-5e1f6dcab192</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @id = 'txtWeb_Login_Id' and @name = 'txtWeb_Login_Id']</value>
      <webElementGuid>f1e4403a-64c8-454c-9dc6-f383fabaee75</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
