<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__pwdPassword</name>
   <tag></tag>
   <elementGuidId>0f98d3cb-ae76-43e5-88fc-0c602d376319</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pwdPassword</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='pwdPassword']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>72a83f76-daff-437a-bf9e-b8bce2a794a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>validate allow_submit</value>
      <webElementGuid>5a3f67d8-8e4d-43ad-80bc-95dccae61e55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>c12f7ea5-c5ce-4a2f-9315-fb2ca4fa9cca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>3bd49e4c-9363-4d10-8a0a-f82c603cc539</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pwdPassword</value>
      <webElementGuid>f69d4032-c06a-4c32-9d61-b097b5d3cd9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pwdPassword</value>
      <webElementGuid>c2c56363-b523-4906-92de-6427f77e578c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pwdPassword&quot;)</value>
      <webElementGuid>9d050463-af1b-4ec6-97da-d898400822e5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='pwdPassword']</value>
      <webElementGuid>4d70f007-09d9-4cf9-9ad7-095e6e20d073</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmsch']/div/div/div[2]/span/input</value>
      <webElementGuid>a0db5952-ea29-4e73-9c70-979446200fed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>5e9f0445-3899-40c7-83f7-d51f27ea2b2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'pwdPassword' and @name = 'pwdPassword']</value>
      <webElementGuid>7a2af246-8865-4a72-a860-3d6d2d69f3c8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
