<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_checkbox</name>
   <tag></tag>
   <elementGuidId>22dc411f-9414-43cd-a7b9-dddabb0c5fc1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.remember-id__text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='frmsch']/div/div/div[3]/label/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>3e6c769b-3117-4bb9-9941-74827a396522</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>remember-id__text</value>
      <webElementGuid>7c2276ed-5243-488f-bd8d-0b22ab23ee2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ログインIDを記憶する</value>
      <webElementGuid>71534eb0-9c4a-49c7-92da-d4175547633c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmsch&quot;)/div[@class=&quot;form__inner form--narrow&quot;]/div[@class=&quot;form__input-wrap&quot;]/div[@class=&quot;remember-id&quot;]/label[@class=&quot;remember-id__label waves-effect waves-light&quot;]/span[@class=&quot;remember-id__text&quot;]</value>
      <webElementGuid>63b55a20-0d69-4675-9c9a-ef6faeb15b40</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmsch']/div/div/div[3]/label/span</value>
      <webElementGuid>28b7e29c-3cf7-43e5-be82-76da3b5e63e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='パスワード'])[1]/following::span[3]</value>
      <webElementGuid>6fc943c3-0236-4f4f-8f4f-f29fcf615a4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ログインID　または　登録メールアドレス'])[1]/following::span[3]</value>
      <webElementGuid>e789df13-fb82-40d2-b8d0-bfa87c62ba0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ログイン'])[3]/preceding::span[1]</value>
      <webElementGuid>a4a5a346-24e4-4c4b-8cb6-8276575a51b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='商品一覧に戻る'])[1]/preceding::span[1]</value>
      <webElementGuid>0dcc5d63-9f4d-419a-83ef-7ded16841164</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ログインIDを記憶する']/parent::*</value>
      <webElementGuid>b8ef2768-f3c2-4b83-828a-441c8fae0afa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/span</value>
      <webElementGuid>70f04503-3d8b-42fb-9607-234ac2fec7d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'ログインIDを記憶する' or . = 'ログインIDを記憶する')]</value>
      <webElementGuid>5f9a05df-f1a7-4495-8dff-74e7228b813d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
